package org.weaw.game;

public record WorldProfilingSnapshot(
        long worldUpdateCpuTimeNs,
        long worldStreamerUpdateCpuTimeNs,
        long lightingCollectionCpuTimeNs,
        long lightingCpuTimeNs,
        long lightingSnapshotLoadedChunksCpuTimeNs,
        long lightingClearCpuTimeNs,
        long lightingSeedCpuTimeNs,
        long lightingPropagateCpuTimeNs,
        long chunkGenerationCpuTimeNs,
        long chunkMeshCpuTimeNs,
        long chunkMeshingSnapshotCpuTimeNs,
        long chunkMeshingFaceClassificationCpuTimeNs,
        long chunkMeshingGreedyMergeCpuTimeNs,
        long chunkMeshingOutputBuildCpuTimeNs,
        long chunkPublishCpuTimeNs,
        long chunkUnloadCpuTimeNs,
        int pendingLightingUpdatesBeforeCollection,
        int pendingLightingUpdatesAfterCollection,
        int lightingBatchSize,
        int lightingAffectedChunkCount,
        int lightingExpandedChunkCount,
        int lightingLoadedChunkCount,
        int lightingLoadedTargetChunkCount,
        int lightingMarkedChunkCount,
        int lightingClearedChunkCount,
        int lightingEmitterCount,
        int lightingSeedNodeCount,
        int lightingPropagationNodeCount,
        int lightingLightWriteCount,
        int lightingBlockedByOpaqueCount,
        int lightingMissingChunkNeighborCount,
        int lightingNoGainCount,
        int lightUploadFullSnapshotCount,
        int lightUploadDeltaCount,
        int lightUploadRefreshedChunkCount,
        int lightUploadFreedChunkCount,
        int lightUploadUploadedChunkCount,
        int lightUploadResidentChunkCount,
        int loadedChunks,
        int queuedTasks,
        int pendingRemesh,
        int pendingUploads,
        int pendingUnloads,
        int chunksPublished,
        int chunksUnloaded,
        int chunksGenerated,
        int chunksMeshed,
        int chunksRemeshed,
        int chunkMeshingAmbientOcclusionFaces,
        int chunkMeshingSampledBlocks,
        int cancelledChunkBuilds
) {
    public static WorldProfilingSnapshot empty() {
        return new WorldProfilingSnapshot(
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0L,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
        );
    }
}
