package org.weaw.runtime;

import java.util.Locale;

public record RuntimeFrameProfile(
        long frame,
        String benchmarkPhase,
        double benchmarkPhaseElapsedSeconds,
        double benchmarkTotalElapsedSeconds,
        boolean streamingConverged,
        boolean benchmarkLoadingConverged,
        double benchmarkLoadingDurationSeconds,
        double fps,
        double frameMs,
        double updateMs,
        double renderMs,
        double windowMs,
        double worldUpdateMs,
        double worldStreamerMs,
        double chunkLightingCollectMs,
        double chunkLightingMs,
        double chunkGenerationMs,
        double chunkMeshMs,
        double chunkMeshingSnapshotMs,
        double chunkMeshingFaceClassificationMs,
        double chunkMeshingGreedyMergeMs,
        double chunkMeshingOutputBuildMs,
        double chunkPublishMs,
        double chunkUnloadMs,
        double renderPassTotalMs,
        double opaquePassMs,
        double cutoutPassMs,
        double transparentPassMs,
        double waterPassMs,
        double blockOutlinePassMs,
        double antiAliasingPassMs,
        double toneMappingPassMs,
        double hudPassMs,
        double debugImGuiPassMs,
        double renderPassGpuTotalMs,
        double opaquePassGpuMs,
        double cutoutPassGpuMs,
        double transparentPassGpuMs,
        double waterPassGpuMs,
        double blockOutlinePassGpuMs,
        double antiAliasingPassGpuMs,
        double toneMappingPassGpuMs,
        double hudPassGpuMs,
        double debugImGuiPassGpuMs,
        int opaqueResidentMeshes,
        int opaqueVisibleMeshes,
        int opaqueDrawCalls,
        int opaqueDrawnFaces,
        double opaqueMeshUploadMs,
        double opaqueLightUploadMs,
        int cutoutResidentMeshes,
        int cutoutVisibleMeshes,
        int cutoutDrawCalls,
        int cutoutDrawnFaces,
        double cutoutMeshUploadMs,
        double cutoutLightUploadMs,
        int transparentResidentMeshes,
        int transparentVisibleMeshes,
        int transparentDrawCalls,
        int transparentDrawnFaces,
        double transparentMeshUploadMs,
        double transparentLightUploadMs,
        double gpuMeshUploadMs,
        double gpuLightUploadMs,
        double lightSnapshotLoadedChunksMs,
        double lightClearMs,
        double lightSeedMs,
        double lightPropagateMs,
        int pendingLightUpdatesBefore,
        int pendingLightUpdatesAfter,
        int lightingBatchChunks,
        int lightingAffectedChunks,
        int lightingExpandedChunks,
        int lightingLoadedChunks,
        int lightingLoadedTargetChunks,
        int lightingMarkedChunks,
        int lightingClearedChunks,
        int lightingEmitters,
        int lightingSeedNodes,
        int lightingPropagationNodes,
        int lightingLightWrites,
        int lightingBlockedByOpaque,
        int lightingMissingChunkNeighbors,
        int lightingNoGain,
        int lightingFullSnapshotChunks,
        int lightingUploadDeltaCount,
        int lightCacheSyncCalls,
        int lightCacheRefreshedChunks,
        int lightCacheFreedChunks,
        int lightCacheUploadedChunks,
        int lightCacheResidentChunks,
        int lightCacheDeferredUploads,
        int lightCacheAllocationFailures,
        int lightCacheEvictions,
        int lightCacheSkippedRetries,
        int lightCacheUrgentUploads,
        int lightCacheBackgroundUploads,
        int lightCacheNewVisibleMisses,
        int lightCachePrefetchUploads,
        int lightCachePrefetchHits,
        int lightCacheFallbackChunks,
        int loadedChunks,
        int visibleChunks,
        int queuedTasks,
        int pendingRemesh,
        int pendingUploads,
        int pendingUnloads,
        int chunksPublished,
        int chunksUnloaded,
        int chunksGenerated,
        int chunksMeshed,
        int chunksRemeshed,
        int chunkMeshingAmbientOcclusionFaces,
        int chunkMeshingSampledBlocks,
        int cancelledChunkBuilds,
        long worldCpuResidentBytes,
        long worldCpuBudgetBytes,
        long worldInFlightBytes,
        long chunkGpuResidentBytes,
        int compactLightingChunks,
        int expandedLightingChunks,
        int requestedRenderDistanceChunks,
        int effectiveRenderDistanceChunks,
        int rejectedLoads,
        String memoryPressureState,
        String adaptiveQualityLevel,
        String graphicsVendor,
        String graphicsRenderer,
        String graphicsVersion,
        int worldStreamingUpdates,
        boolean sparseStreamingEnabled,
        int desiredMaterializedChunks,
        int virtualEmptyChunks,
        int virtualUniformChunks,
        int interactionBubbleChunks,
        int legacyCandidateChunks,
        int avoidedChunkCandidates,
        double chunkAvoidancePercent,
        int classificationCacheColumns,
        long classificationCacheHits,
        long classificationCacheMisses,
        double classificationCacheHitPercent
) {
    public static String csvHeader() {
        return String.join(",",
                "frame",
                "benchmark_phase",
                "benchmark_phase_elapsed_seconds",
                "benchmark_total_elapsed_seconds",
                "streaming_converged",
                "benchmark_loading_converged",
                "benchmark_loading_duration_seconds",
                "fps",
                "frame_ms",
                "update_ms",
                "render_ms",
                "window_ms",
                "world_update_ms",
                "world_streamer_ms",
                "chunk_light_collect_ms",
                "chunk_light_ms",
                "chunk_gen_ms",
                "chunk_mesh_ms",
                "chunk_meshing_snapshot_ms",
                "chunk_meshing_face_classification_ms",
                "chunk_meshing_greedy_merge_ms",
                "chunk_meshing_output_build_ms",
                "chunk_publish_ms",
                "chunk_unload_ms",
                "render_pass_total_ms",
                "opaque_pass_ms",
                "cutout_pass_ms",
                "transparent_pass_ms",
                "water_pass_ms",
                "block_outline_pass_ms",
                "anti_aliasing_pass_ms",
                "tone_mapping_pass_ms",
                "hud_pass_ms",
                "debug_imgui_pass_ms",
                "render_pass_gpu_total_ms",
                "opaque_pass_gpu_ms",
                "cutout_pass_gpu_ms",
                "transparent_pass_gpu_ms",
                "water_pass_gpu_ms",
                "block_outline_pass_gpu_ms",
                "anti_aliasing_pass_gpu_ms",
                "tone_mapping_pass_gpu_ms",
                "hud_pass_gpu_ms",
                "debug_imgui_pass_gpu_ms",
                "opaque_resident_meshes",
                "opaque_visible_meshes",
                "opaque_draw_calls",
                "opaque_drawn_faces",
                "opaque_mesh_upload_ms",
                "opaque_light_upload_ms",
                "cutout_resident_meshes",
                "cutout_visible_meshes",
                "cutout_draw_calls",
                "cutout_drawn_faces",
                "cutout_mesh_upload_ms",
                "cutout_light_upload_ms",
                "transparent_resident_meshes",
                "transparent_visible_meshes",
                "transparent_draw_calls",
                "transparent_drawn_faces",
                "transparent_mesh_upload_ms",
                "transparent_light_upload_ms",
                "gpu_mesh_upload_ms",
                "gpu_light_upload_ms",
                "light_snapshot_loaded_chunks_ms",
                "light_clear_ms",
                "light_seed_ms",
                "light_propagate_ms",
                "pending_light_updates_before",
                "pending_light_updates_after",
                "lighting_batch_chunks",
                "lighting_affected_chunks",
                "lighting_expanded_chunks",
                "lighting_loaded_chunks",
                "lighting_loaded_target_chunks",
                "lighting_marked_chunks",
                "lighting_cleared_chunks",
                "lighting_emitters",
                "lighting_seed_nodes",
                "lighting_propagation_nodes",
                "lighting_light_writes",
                "lighting_blocked_by_opaque",
                "lighting_missing_chunk_neighbors",
                "lighting_no_gain",
                "lighting_full_snapshot_chunks",
                "lighting_upload_delta_count",
                "light_cache_sync_calls",
                "light_cache_refreshed_chunks",
                "light_cache_freed_chunks",
                "light_cache_uploaded_chunks",
                "light_cache_resident_chunks",
                "light_cache_deferred_uploads",
                "light_cache_allocation_failures",
                "light_cache_evictions",
                "light_cache_skipped_retries",
                "light_cache_urgent_uploads",
                "light_cache_background_uploads",
                "light_cache_new_visible_misses",
                "light_cache_prefetch_uploads",
                "light_cache_prefetch_hits",
                "light_cache_fallback_chunks",
                "loaded_chunks",
                "visible_chunks",
                "queued_tasks",
                "pending_remesh",
                "pending_uploads",
                "pending_unloads",
                "chunks_published",
                "chunks_unloaded",
                "chunks_generated",
                "chunks_meshed",
                "chunks_remeshed",
                "chunk_meshing_ao_faces",
                "chunk_meshing_sampled_blocks",
                "cancelled_chunk_builds",
                "world_cpu_resident_bytes",
                "world_cpu_budget_bytes",
                "world_in_flight_bytes",
                "chunk_gpu_resident_bytes",
                "compact_lighting_chunks",
                "expanded_lighting_chunks",
                "requested_render_distance_chunks",
                "effective_render_distance_chunks",
                "rejected_loads",
                "memory_pressure_state",
                "adaptive_quality_level",
                "graphics_vendor",
                "graphics_renderer",
                "graphics_version",
                "world_streaming_updates",
                "sparse_streaming_enabled",
                "desired_materialized_chunks",
                "virtual_empty_chunks",
                "virtual_uniform_chunks",
                "interaction_bubble_chunks",
                "legacy_candidate_chunks",
                "avoided_chunk_candidates",
                "chunk_avoidance_percent",
                "classification_cache_columns",
                "classification_cache_hits",
                "classification_cache_misses",
                "classification_cache_hit_percent"
        );
    }

    public String toCsvRow() {
        return String.join(",",
                Long.toString(frame),
                benchmarkPhase,
                format(benchmarkPhaseElapsedSeconds),
                format(benchmarkTotalElapsedSeconds),
                Boolean.toString(streamingConverged),
                Boolean.toString(benchmarkLoadingConverged),
                format(benchmarkLoadingDurationSeconds),
                format(fps),
                format(frameMs),
                format(updateMs),
                format(renderMs),
                format(windowMs),
                format(worldUpdateMs),
                format(worldStreamerMs),
                format(chunkLightingCollectMs),
                format(chunkLightingMs),
                format(chunkGenerationMs),
                format(chunkMeshMs),
                format(chunkMeshingSnapshotMs),
                format(chunkMeshingFaceClassificationMs),
                format(chunkMeshingGreedyMergeMs),
                format(chunkMeshingOutputBuildMs),
                format(chunkPublishMs),
                format(chunkUnloadMs),
                format(renderPassTotalMs),
                format(opaquePassMs),
                format(cutoutPassMs),
                format(transparentPassMs),
                format(waterPassMs),
                format(blockOutlinePassMs),
                format(antiAliasingPassMs),
                format(toneMappingPassMs),
                format(hudPassMs),
                format(debugImGuiPassMs),
                format(renderPassGpuTotalMs),
                format(opaquePassGpuMs),
                format(cutoutPassGpuMs),
                format(transparentPassGpuMs),
                format(waterPassGpuMs),
                format(blockOutlinePassGpuMs),
                format(antiAliasingPassGpuMs),
                format(toneMappingPassGpuMs),
                format(hudPassGpuMs),
                format(debugImGuiPassGpuMs),
                Integer.toString(opaqueResidentMeshes),
                Integer.toString(opaqueVisibleMeshes),
                Integer.toString(opaqueDrawCalls),
                Integer.toString(opaqueDrawnFaces),
                format(opaqueMeshUploadMs),
                format(opaqueLightUploadMs),
                Integer.toString(cutoutResidentMeshes),
                Integer.toString(cutoutVisibleMeshes),
                Integer.toString(cutoutDrawCalls),
                Integer.toString(cutoutDrawnFaces),
                format(cutoutMeshUploadMs),
                format(cutoutLightUploadMs),
                Integer.toString(transparentResidentMeshes),
                Integer.toString(transparentVisibleMeshes),
                Integer.toString(transparentDrawCalls),
                Integer.toString(transparentDrawnFaces),
                format(transparentMeshUploadMs),
                format(transparentLightUploadMs),
                format(gpuMeshUploadMs),
                format(gpuLightUploadMs),
                format(lightSnapshotLoadedChunksMs),
                format(lightClearMs),
                format(lightSeedMs),
                format(lightPropagateMs),
                Integer.toString(pendingLightUpdatesBefore),
                Integer.toString(pendingLightUpdatesAfter),
                Integer.toString(lightingBatchChunks),
                Integer.toString(lightingAffectedChunks),
                Integer.toString(lightingExpandedChunks),
                Integer.toString(lightingLoadedChunks),
                Integer.toString(lightingLoadedTargetChunks),
                Integer.toString(lightingMarkedChunks),
                Integer.toString(lightingClearedChunks),
                Integer.toString(lightingEmitters),
                Integer.toString(lightingSeedNodes),
                Integer.toString(lightingPropagationNodes),
                Integer.toString(lightingLightWrites),
                Integer.toString(lightingBlockedByOpaque),
                Integer.toString(lightingMissingChunkNeighbors),
                Integer.toString(lightingNoGain),
                Integer.toString(lightingFullSnapshotChunks),
                Integer.toString(lightingUploadDeltaCount),
                Integer.toString(lightCacheSyncCalls),
                Integer.toString(lightCacheRefreshedChunks),
                Integer.toString(lightCacheFreedChunks),
                Integer.toString(lightCacheUploadedChunks),
                Integer.toString(lightCacheResidentChunks),
                Integer.toString(lightCacheDeferredUploads),
                Integer.toString(lightCacheAllocationFailures),
                Integer.toString(lightCacheEvictions),
                Integer.toString(lightCacheSkippedRetries),
                Integer.toString(lightCacheUrgentUploads),
                Integer.toString(lightCacheBackgroundUploads),
                Integer.toString(lightCacheNewVisibleMisses),
                Integer.toString(lightCachePrefetchUploads),
                Integer.toString(lightCachePrefetchHits),
                Integer.toString(lightCacheFallbackChunks),
                Integer.toString(loadedChunks),
                Integer.toString(visibleChunks),
                Integer.toString(queuedTasks),
                Integer.toString(pendingRemesh),
                Integer.toString(pendingUploads),
                Integer.toString(pendingUnloads),
                Integer.toString(chunksPublished),
                Integer.toString(chunksUnloaded),
                Integer.toString(chunksGenerated),
                Integer.toString(chunksMeshed),
                Integer.toString(chunksRemeshed),
                Integer.toString(chunkMeshingAmbientOcclusionFaces),
                Integer.toString(chunkMeshingSampledBlocks),
                Integer.toString(cancelledChunkBuilds),
                Long.toString(worldCpuResidentBytes),
                Long.toString(worldCpuBudgetBytes),
                Long.toString(worldInFlightBytes),
                Long.toString(chunkGpuResidentBytes),
                Integer.toString(compactLightingChunks),
                Integer.toString(expandedLightingChunks),
                Integer.toString(requestedRenderDistanceChunks),
                Integer.toString(effectiveRenderDistanceChunks),
                Integer.toString(rejectedLoads),
                memoryPressureState,
                adaptiveQualityLevel,
                csvText(graphicsVendor),
                csvText(graphicsRenderer),
                csvText(graphicsVersion),
                Integer.toString(worldStreamingUpdates),
                Boolean.toString(sparseStreamingEnabled),
                Integer.toString(desiredMaterializedChunks),
                Integer.toString(virtualEmptyChunks),
                Integer.toString(virtualUniformChunks),
                Integer.toString(interactionBubbleChunks),
                Integer.toString(legacyCandidateChunks),
                Integer.toString(avoidedChunkCandidates),
                format(chunkAvoidancePercent),
                Integer.toString(classificationCacheColumns),
                Long.toString(classificationCacheHits),
                Long.toString(classificationCacheMisses),
                format(classificationCacheHitPercent)
        );
    }

    private static String format(double value) {
        return String.format(Locale.ROOT, "%.4f", value);
    }

    private static String csvText(String value) {
        if (value == null) {
            return "";
        }
        return '"' + value.replace("\"", "\"\"") + '"';
    }
}
